# user spec file, compiler rf_sp_hde, version r0p0

activity_factor = 50
atf = off
back_biasing = off
bits = 64
bmux = off
bus_notation = on
check_instname = off
corners = tt_0p90v_0p90v_25c
cust_comment = This\ is\ a\ memory\ instance
diodes = on
drive = 6
ema = on
frequency = 500
instname = sram_28nm_64x128_SP
left_bus_delim = [
libertyviewstyle = nldm
libname = sram_28nm_64x128_SP
mux = 2
mvt = BASE
name_case = lower
pipeline = off
power_gating = off
power_type = otc
pwr_gnd_rename = vddpe:VDDPE,vddce:VDDCE,vsse:VSSE
rcols = 2
redundancy = off
retention = on
right_bus_delim = ]
rrows = 0
ser = none
site_def = off
top_layer = m5-m10
words = 128
wp_size = 1
write_mask = on
write_thru = off
