#=========================================================================
# mock-push
#=========================================================================
# Mock up a node with outputs matching the inputs of the target node
#
# Author : Christopher Torng
# Date   : March 17, 2020
#

name: mock-push

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

# These outputs will be filled in at graph construction time

outputs: []

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs && eval {cmd}

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  cmd: echo Placeholder for miscellaneous commands


