#=========================================================================
# QRouter Routing
#=========================================================================
# Author : Christopher Torng
# Date   : June 18, 2019
#

name: open-qrouter-route

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.def

outputs:
  - design.def

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # qrouter
  - qrouter -nog -s qrouter.cfg
  # outputs
  - mkdir -p outputs && cd outputs
  - ln -sf ../*.def design.def

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined


