#=========================================================================
# Mentor Calibre -- Chip Art
#=========================================================================
# Author : Christopher Torng
# Date   : May 29, 2020
#

name: mentor-calibre-chipart

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - shapes.py

outputs:
  - chipart.gds

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - make

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

#parameters:

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - calibredrv -m chipart.gds \
               -l inputs/adk/calibre.layerprops


