#=========================================================================
# Mentor Calibre DRC
#=========================================================================
# Author : Christopher Torng
# Date   : November 5, 2019
#

name: mentor-calibre-drc

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - design_merged.gds
  - adk

outputs:
  - drc.results
  - drc.summary

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - if [ -f "inputs/adk/{drc_env_setup}" ]; then source inputs/adk/{drc_env_setup}; fi
  - envsubst < drc.runset.template > drc.runset
  - calibre -gui -drc -batch -runset drc.runset
  - mkdir -p outputs && cd outputs
  - ln -sf ../drc.results
  - ln -sf ../drc.summary

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  # Use the rule deck "inputs/adk/${drc_rule_deck}"
  drc_rule_deck: calibre-drc-block.rule
  # Optional: if the technology accepts DRC params
  # as environment variables, source this script
  # to set environment variables before running.
  drc_env_setup: undefined

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - calibredrv -m inputs/design_merged.gds \
               -l inputs/adk/calibre.layerprops \
               -rve -drc drc.results

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'calibre' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design_merged.gds' )


