#=========================================================================
# OpenROAD Flow Scripts
#=========================================================================
# Mirror nodes that track ORFS flow scripts
#
# This flow setup node produces a base docker image as a tarball, which
# contains the OpenROAD flow scripts environment. The image contains all
# of the installed tools and is passed to all downstream ORFS mflowgen
# nodes.
#
# Author : Christopher Torng
# Date   : June 17, 2024
#

name: orfs-docker-setup

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - orfs-docker-image.tar

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - echo -e "\n- Pulling orfs docker image -- $orfs_image\n"
  - docker pull $orfs_image
  - CONTAINER=$(docker run -it -d $orfs_image)
  # copy makefile patch scripts to docker
  - echo -e "\n- Moving makefile-patch-scripts folder to container\n"
  - docker cp ./makefile-patch-scripts $CONTAINER:/OpenROAD-flow-scripts/
  # run makefile-patches.py
  - echo -e "\n- Exe python makefile patches\n"
  - docker exec $CONTAINER bash -c "cd makefile-patch-scripts && python3 makefile-patches.py"
  # - docker cp $CONTAINER:/OpenROAD-flow-scripts/flow/Makefile ../../split_scripts # just to debug the script performance
  # commit the patches
  - echo -e "\n- Commit the makefile-patches to the image\n"
  - docker commit $CONTAINER $orfs_image
  - echo -e "\n- Saving orfs docker image as tarball for output\n"
  - docker save -o orfs-docker-image.tar $orfs_image
  - docker rm -f $CONTAINER
  # - docker rmi -f $orfs_image # Comment this out for performance
  - mkdir -p outputs && cd outputs
  - ln -sf ../orfs-docker-image.tar

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  clock_period: 1.0
  adk: undefined
  # Pick an image from Docker Hub "mflowgen/openroad-flow-scripts-base"
  # - https://hub.docker.com/repository/docker/mflowgen/openroad-flow-scripts-base/general
  orfs_image: mflowgen/openroad-flow-scripts-base:2024-0621-f0caba6

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'docker' ) # tool check

postconditions:

  - assert File( 'outputs/orfs-docker-image.tar' )  # must exist


