#=========================================================================
# Synopsys PTPX -- RTL
#=========================================================================

name: synopsys-ptpx-rtl

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.vcs.v
  - design.spef.gz
  - design.pt.sdc
  - run.saif
  - design.namemap

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - pt_shell -file pt_px.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
  design_name: undefined

