#=========================================================================
# Cadence Innovus
#=========================================================================
# Author : Christopher Torng
# Date   : January 13, 2020
#

name: cadence-innovus-power

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - innovus-foundation-flow
  - adk
  - design.sdc
  - design.checkpoint

outputs:
  - design.checkpoint

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - ln -sf inputs/innovus-foundation-flow
  - if [[ "x$enable_gui" == "xTrue" ]]; then gui_flag=""; else gui_flag="-nowin"; fi
  - innovus -overwrite -64 $gui_flag -init START.tcl -log logs/run.log
  # Outputs
  - cd outputs
  - ln -sf ../checkpoints/design.checkpoint

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  # Enable Innovus GUI
  enable_gui: true
  # Subscript execute order
  order:
    - globalnetconnect.tcl
    - main.tcl

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - innovus -overwrite -64
    -init innovus-foundation-flow/custom-scripts/run-debug.tcl
    -log logs/debug.log

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'innovus' )                         # tool check
  - assert File( 'inputs/innovus-foundation-flow' )  # must exist
  - assert File( 'inputs/adk' )                      # must exist
  - assert File( 'inputs/design.sdc' )               # must exist
  - assert File( 'inputs/design.checkpoint' )        # must exist

postconditions:

  - assert File( 'outputs/design.checkpoint' )       # must exist


