#=========================================================================
# Cadence Innovus
#=========================================================================
# Author : Christopher Torng
# Date   : October 30, 2019
#

name: cadence-innovus-init

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - innovus-foundation-flow
  - adk
  - design.v
  - design.sdc

outputs:
  - design.checkpoint

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - ln -sf inputs/innovus-foundation-flow
  - innovus -overwrite -64 -nowin -init START.tcl -log logs/run.log

  # Outputs
  - cd outputs
  - ln -sf ../checkpoints/design.checkpoint

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  # Placement density of 70% is reasonable
  core_density_target: 0.70
  # Subscript execute order
  order:
    - pre-init.tcl
    - main.tcl
    - dont-use.tcl
    - quality-of-life.tcl
    - floorplan.tcl
    - add-endcaps-welltaps.tcl
    - pin-assignments.tcl
    - make-path-groups.tcl
    - reporting.tcl

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - innovus -overwrite -64
    -init innovus-foundation-flow/custom-scripts/run-debug.tcl
    -log logs/debug.log

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'innovus' )                         # tool check
  - assert File( 'inputs/innovus-foundation-flow' )  # must exist
  - assert File( 'inputs/adk' )                      # must exist
  - assert File( 'inputs/design.v' )                 # must exist
  - assert File( 'inputs/design.sdc' )               # must exist

postconditions:

  - assert File( 'outputs/design.checkpoint' )       # must exist

  # Check for consistent library units for capacitance
  #
  #     **WARN: (IMPTS-17): Inconsistency detected in the capacitance
  #     units specified among the timing libraries being used. Default
  #     system capacitance unit of 1pF will be used. Use the
  #     'setLibraryUnit' command to set a specific capacitance unit.
  #
  # If library units are mismatched, then unitless commands like
  # "set_load" can be inconsistent across tools. Each tool seems to handle
  # unit conflicts differently, so we assert here to catch these cases.

  - assert 'Inconsistency detected in the capacitance units'
      not in File( 'logs/run.log' )



