outputs/pb_on_bread.txt: inputs/slice_of_bread.txt
	mkdir -p outputs
	echo ' \/\/\/\/\/\/  <-- peanut butter' > outputs/peanut_butter_on_bread.txt
	cat inputs/slice_of_bread.txt >> outputs/peanut_butter_on_bread.txt

