#=========================================================================
# Yosys Synthesis
#=========================================================================
# Author : Christopher Torng
# Date   : June 18, 2019
#

name: open-yosys-synthesis

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.v

outputs:
  - design.v
  - synth.stats.txt

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # make the RTL more yosys-friendly
  - sed -e "s/\\$/_/g" inputs/design.v > design.name_mangled.v
  # synthesis
  - python generate-synth.py
  - yosys -s synth.ys -l synth.log
  # outputs
  - mkdir -p outputs && cd outputs
  - ln -sf ../*.mapped.v design.v
  - ln -sf ../stats.txt synth.stats.txt

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  clock_period: 2.0


