gcd-top:
	vcs -full64 -sverilog -debug_pp gcd-test.v -v GcdTop.v

fifo-top:
	vcs -full64 -sverilog -debug_pp fifo-test.v -v FifoTop.v

fifo-isolated:
	vcs -full64 -sverilog -debug_pp fifo-isolated-test.v -v BisynchronousNormalQueue.v
