#=========================================================================
# Synopsys DC lib2db
#=========================================================================

name: synopsys-dc-lib2db

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - design.lib

outputs:
  - design.db

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - make

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'dc_shell' )                # tool check
  - assert File( 'inputs/design.lib' )       # must exist

postconditions:
  - assert File( 'outputs/design.db' )       # must exist

