#=========================================================================
# Cadence Pegasus DRC
#=========================================================================
# Author : Maxwell Strange
# Date   : October 14, 2020
#

name: cadence-pegasus-drc

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - design_merged.gds
  - adk

outputs:
  - drc.results
  - drc.summary

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  # Use the rule deck "inputs/adk/${drc_rule_deck}"
  drc_rule_deck: pegasus-drc-block.rule

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - source run_drc.sh

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - pegasusDesignReview -data inputs/design_merged.gds:DRC_RES.db

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'pegasus' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design_merged.gds' )


