#=========================================================================
# Cadence Innovus
#=========================================================================
# Author : Christopher Torng
# Date   : October 30, 2019
#

name: cadence-innovus-signoff

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - innovus-foundation-flow
  - adk
  - design.checkpoint

outputs:
  - design.checkpoint
  - design.gds.gz
  - design-merged.gds
  - design.lvs.v
  - design.vcs.v
  - design.vcs.pg.v
  - design.lef
  - design.pt.sdc
  - design.sdf
  - design.virtuoso.v
  - design.spef.gz
  - design.rcbest.spef.gz
  - design.def.gz

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - ln -sf inputs/innovus-foundation-flow
  - innovus -overwrite -64 -nowin -init START.tcl -log logs/run.log

  # Outputs
  - cd outputs
  - ln -sf ../checkpoints/design.checkpoint
  - ln -sf ../typical.spef.gz             design.spef.gz
  - ln -sf ../rcbest.spef.gz              design.rcbest.spef.gz
  - ln -sf ../results/*.gds.gz            design.gds.gz
  - ln -sf ../results/*-merged.gds        design-merged.gds
  - ln -sf ../results/*.lvs.v             design.lvs.v
  - ln -sf ../results/*.vcs.v             design.vcs.v
  - ln -sf ../results/*.vcs.pg.v          design.vcs.pg.v
  - ln -sf ../results/*.lef               design.lef
  - ln -sf ../results/*.pt.sdc            design.pt.sdc
  - ln -sf ../results/*.sdf               design.sdf
  - ln -sf ../results/*.virtuoso.v        design.virtuoso.v
  - ln -sf ../results/*.def.gz            design.def.gz

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  order:
    - main.tcl
    - generate-results.tcl
    - reporting.tcl

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - innovus -overwrite -64
    -init innovus-foundation-flow/custom-scripts/run-debug.tcl
    -log logs/debug.log

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'innovus' )                         # tool check
  - assert File( 'inputs/innovus-foundation-flow' )  # must exist
  - assert File( 'inputs/adk' )                      # must exist
  - assert File( 'inputs/design.checkpoint' )        # must exist

postconditions:

  - assert File( 'outputs/design.checkpoint' )       # must exist


