#=========================================================================
# VCD to SAIF
#=========================================================================
# Author : Yanghui Ou
#   Date : Aug 15, 2019
#

name: synopsys-vcd2saif-convert

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - run.vcd

outputs:
  - run.saif

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - vcd2saif -input inputs/run.vcd -output outputs/run.saif

