/* verilator lint_off WIDTH */

//===============================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="GcdXcelHLS,hls_ip_2015_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.100000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=190,HLS_SYN_LUT=398}" *)

module GcdXcelHLS (
        ap_clk,
        ap_rst,
        xcelreq_V_bits_V,
        xcelreq_V_bits_V_ap_vld,
        xcelreq_V_bits_V_ap_ack,
        xcelresp_V_bits_V,
        xcelresp_V_bits_V_ap_vld,
        xcelresp_V_bits_V_ap_ack
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_st3_fsm_2 = 4'b100;
parameter    ap_ST_st4_fsm_3 = 4'b1000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_2A = 32'b101010;
parameter    ap_const_lv32_2B = 32'b101011;
parameter    ap_const_lv32_2C = 32'b101100;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv32_31 = 32'b110001;
parameter    ap_const_lv32_38 = 32'b111000;
parameter    ap_const_lv33_100000000 = 33'b100000000000000000000000000000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input  [56:0] xcelreq_V_bits_V;
input   xcelreq_V_bits_V_ap_vld;
output   xcelreq_V_bits_V_ap_ack;
output  [51:0] xcelresp_V_bits_V;
output   xcelresp_V_bits_V_ap_vld;
input   xcelresp_V_bits_V_ap_ack;

reg xcelreq_V_bits_V_ap_ack;
reg[51:0] xcelresp_V_bits_V;
reg xcelresp_V_bits_V_ap_vld;
reg   [56:0] xcelWrapper_m_req_bits_V_reg_288;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_25;
wire   [0:0] tmp_4_fu_128_p3;
reg    ap_sig_ioackin_xcelresp_V_bits_V_ap_ack;
wire   [31:0] XcelWrapper_3_m_xregs_V16_1_i_fu_176_p3;
wire   [31:0] XcelWrapper_3_m_xregs_V2_1_i_fu_192_p3;
wire   [31:0] opA_V_assign_2_fu_249_p3;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_52;
wire   [0:0] tmp_1_fu_225_p2;
wire   [31:0] opB_V_assign_2_fu_257_p3;
reg   [31:0] xcelWrapper_m_xregs_1_V_reg_83;
reg   [31:0] xcelWrapper_m_xregs_2_V_reg_95;
reg   [31:0] p_Repl2_1_reg_107;
reg   [31:0] opB_assign_reg_118;
wire   [51:0] p_Result_s_fu_214_p4;
wire   [51:0] p_Result_1_fu_277_p4;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_78;
reg    ap_reg_ioackin_xcelresp_V_bits_V_ap_ack = 1'b0;
wire   [1:0] p_Result_t_i_fu_146_p4;
wire   [0:0] sel_tmp_i_fu_156_p2;
wire   [31:0] p_Result_i_fu_136_p4;
wire   [0:0] sel_tmp6_i_fu_162_p2;
wire   [31:0] sel_tmp9_i_fu_168_p3;
wire   [31:0] sel_tmp21_i_fu_184_p3;
wire   [7:0] p_Repl2_2_fu_200_p4;
wire   [10:0] p_Repl2_s_fu_210_p1;
wire   [0:0] tmp_2_fu_231_p2;
wire   [31:0] opA_V_assign_1_fu_237_p2;
wire   [31:0] opB_V_assign_1_fu_243_p2;
wire   [8:0] tmp_3_fu_268_p4;
wire   [10:0] p_Repl2_3_fu_265_p1;
reg   [3:0] ap_NS_fsm;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_xcelresp_V_bits_V_ap_ack assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_xcelresp_V_bits_V_ap_ack
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_xcelresp_V_bits_V_ap_ack <= ap_const_logic_0;
    end else begin
        if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_4_fu_128_p3 == ap_const_lv1_0) & ~((xcelreq_V_bits_V_ap_vld == ap_const_logic_0) | (~(tmp_4_fu_128_p3 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_bits_V_ap_ack)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_bits_V_ap_ack)))) begin
            ap_reg_ioackin_xcelresp_V_bits_V_ap_ack <= ap_const_logic_0;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_4_fu_128_p3 == ap_const_lv1_0) & ~(xcelreq_V_bits_V_ap_vld == ap_const_logic_0) & (ap_const_logic_1 == xcelresp_V_bits_V_ap_ack)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_logic_1 == xcelresp_V_bits_V_ap_ack)))) begin
            ap_reg_ioackin_xcelresp_V_bits_V_ap_ack <= ap_const_logic_1;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_4_fu_128_p3 == ap_const_lv1_0) & ~((xcelreq_V_bits_V_ap_vld == ap_const_logic_0) | (~(tmp_4_fu_128_p3 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_bits_V_ap_ack))))) begin
        opB_assign_reg_118 <= xcelWrapper_m_xregs_2_V_reg_95;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == tmp_1_fu_225_p2))) begin
        opB_assign_reg_118 <= opB_V_assign_2_fu_257_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_4_fu_128_p3 == ap_const_lv1_0) & ~((xcelreq_V_bits_V_ap_vld == ap_const_logic_0) | (~(tmp_4_fu_128_p3 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_bits_V_ap_ack))))) begin
        p_Repl2_1_reg_107 <= xcelWrapper_m_xregs_1_V_reg_83;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == tmp_1_fu_225_p2))) begin
        p_Repl2_1_reg_107 <= opA_V_assign_2_fu_249_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~((xcelreq_V_bits_V_ap_vld == ap_const_logic_0) | (~(tmp_4_fu_128_p3 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_bits_V_ap_ack))))) begin
        xcelWrapper_m_req_bits_V_reg_288 <= xcelreq_V_bits_V;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_4_fu_128_p3 == ap_const_lv1_0) & ~((xcelreq_V_bits_V_ap_vld == ap_const_logic_0) | (~(tmp_4_fu_128_p3 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_bits_V_ap_ack))))) begin
        xcelWrapper_m_xregs_1_V_reg_83 <= XcelWrapper_3_m_xregs_V16_1_i_fu_176_p3;
        xcelWrapper_m_xregs_2_V_reg_95 <= XcelWrapper_3_m_xregs_V2_1_i_fu_192_p3;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_25)
begin
    if (ap_sig_bdd_25) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_52)
begin
    if (ap_sig_bdd_52) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_78)
begin
    if (ap_sig_bdd_78) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_ioackin_xcelresp_V_bits_V_ap_ack assign process. ///
always @ (xcelresp_V_bits_V_ap_ack or ap_reg_ioackin_xcelresp_V_bits_V_ap_ack)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_bits_V_ap_ack)) begin
        ap_sig_ioackin_xcelresp_V_bits_V_ap_ack = xcelresp_V_bits_V_ap_ack;
    end else begin
        ap_sig_ioackin_xcelresp_V_bits_V_ap_ack = ap_const_logic_1;
    end
end

/// xcelreq_V_bits_V_ap_ack assign process. ///
always @ (xcelreq_V_bits_V_ap_vld or ap_sig_cseq_ST_st2_fsm_1 or tmp_4_fu_128_p3 or ap_sig_ioackin_xcelresp_V_bits_V_ap_ack)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~((xcelreq_V_bits_V_ap_vld == ap_const_logic_0) | (~(tmp_4_fu_128_p3 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_bits_V_ap_ack))))) begin
        xcelreq_V_bits_V_ap_ack = ap_const_logic_1;
    end else begin
        xcelreq_V_bits_V_ap_ack = ap_const_logic_0;
    end
end

/// xcelresp_V_bits_V assign process. ///
always @ (xcelreq_V_bits_V_ap_vld or ap_sig_cseq_ST_st2_fsm_1 or tmp_4_fu_128_p3 or p_Result_s_fu_214_p4 or p_Result_1_fu_277_p4 or ap_sig_cseq_ST_st4_fsm_3)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        xcelresp_V_bits_V = p_Result_1_fu_277_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_4_fu_128_p3 == ap_const_lv1_0) & ~(xcelreq_V_bits_V_ap_vld == ap_const_logic_0))) begin
        xcelresp_V_bits_V = p_Result_s_fu_214_p4;
    end else begin
        xcelresp_V_bits_V = 'bx;
    end
end

/// xcelresp_V_bits_V_ap_vld assign process. ///
always @ (xcelreq_V_bits_V_ap_vld or ap_sig_cseq_ST_st2_fsm_1 or tmp_4_fu_128_p3 or ap_sig_cseq_ST_st4_fsm_3 or ap_reg_ioackin_xcelresp_V_bits_V_ap_ack)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_4_fu_128_p3 == ap_const_lv1_0) & ~(xcelreq_V_bits_V_ap_vld == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_bits_V_ap_ack)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_bits_V_ap_ack)))) begin
        xcelresp_V_bits_V_ap_vld = ap_const_logic_1;
    end else begin
        xcelresp_V_bits_V_ap_vld = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (xcelreq_V_bits_V_ap_vld or ap_CS_fsm or tmp_4_fu_128_p3 or ap_sig_ioackin_xcelresp_V_bits_V_ap_ack or tmp_1_fu_225_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((~(tmp_4_fu_128_p3 == ap_const_lv1_0) & ~((xcelreq_V_bits_V_ap_vld == ap_const_logic_0) | (~(tmp_4_fu_128_p3 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_bits_V_ap_ack))))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else if (((tmp_4_fu_128_p3 == ap_const_lv1_0) & ~((xcelreq_V_bits_V_ap_vld == ap_const_logic_0) | (~(tmp_4_fu_128_p3 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_bits_V_ap_ack))))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if ((ap_const_lv1_0 == tmp_1_fu_225_p2)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_bits_V_ap_ack)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign XcelWrapper_3_m_xregs_V16_1_i_fu_176_p3 = ((sel_tmp6_i_fu_162_p2[0:0]===1'b1)? xcelWrapper_m_xregs_1_V_reg_83: sel_tmp9_i_fu_168_p3);
assign XcelWrapper_3_m_xregs_V2_1_i_fu_192_p3 = ((sel_tmp6_i_fu_162_p2[0:0]===1'b1)? xcelWrapper_m_xregs_2_V_reg_95: sel_tmp21_i_fu_184_p3);

/// ap_sig_bdd_25 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_25 = (ap_CS_fsm[ap_const_lv32_1] == ap_const_lv1_1);
end

/// ap_sig_bdd_52 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_52 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_78 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_78 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end
assign opA_V_assign_1_fu_237_p2 = (p_Repl2_1_reg_107 - opB_assign_reg_118);
assign opA_V_assign_2_fu_249_p3 = ((tmp_2_fu_231_p2[0:0]===1'b1)? opA_V_assign_1_fu_237_p2: p_Repl2_1_reg_107);
assign opB_V_assign_1_fu_243_p2 = (opB_assign_reg_118 - p_Repl2_1_reg_107);
assign opB_V_assign_2_fu_257_p3 = ((tmp_2_fu_231_p2[0:0]===1'b1)? opB_assign_reg_118: opB_V_assign_1_fu_243_p2);
assign p_Repl2_2_fu_200_p4 = {{xcelreq_V_bits_V[ap_const_lv32_38 : ap_const_lv32_31]}};
assign p_Repl2_3_fu_265_p1 = xcelWrapper_m_req_bits_V_reg_288[10:0];
assign p_Repl2_s_fu_210_p1 = xcelreq_V_bits_V[10:0];
assign p_Result_1_fu_277_p4 = {{{tmp_3_fu_268_p4}, {p_Repl2_1_reg_107}}, {p_Repl2_3_fu_265_p1}};
assign p_Result_i_fu_136_p4 = {{xcelreq_V_bits_V[ap_const_lv32_2A : ap_const_lv32_B]}};
assign p_Result_s_fu_214_p4 = {{{p_Repl2_2_fu_200_p4}, {ap_const_lv33_100000000}}, {p_Repl2_s_fu_210_p1}};
assign p_Result_t_i_fu_146_p4 = {{xcelreq_V_bits_V[ap_const_lv32_2C : ap_const_lv32_2B]}};
assign sel_tmp21_i_fu_184_p3 = ((sel_tmp_i_fu_156_p2[0:0]===1'b1)? xcelWrapper_m_xregs_2_V_reg_95: p_Result_i_fu_136_p4);
assign sel_tmp6_i_fu_162_p2 = (p_Result_t_i_fu_146_p4 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp9_i_fu_168_p3 = ((sel_tmp_i_fu_156_p2[0:0]===1'b1)? p_Result_i_fu_136_p4: xcelWrapper_m_xregs_1_V_reg_83);
assign sel_tmp_i_fu_156_p2 = (p_Result_t_i_fu_146_p4 == ap_const_lv2_1? 1'b1: 1'b0);
assign tmp_1_fu_225_p2 = (p_Repl2_1_reg_107 == opB_assign_reg_118? 1'b1: 1'b0);
assign tmp_2_fu_231_p2 = (p_Repl2_1_reg_107 > opB_assign_reg_118? 1'b1: 1'b0);
assign tmp_3_fu_268_p4 = {{xcelWrapper_m_req_bits_V_reg_288[ap_const_lv32_38 : ap_const_lv32_30]}};
assign tmp_4_fu_128_p3 = xcelreq_V_bits_V[ap_const_lv32_30];


endmodule //GcdXcelHLS


/* lint_on */
